### ISSUE TITLE
more helpful error message

### ISSUE THREAD

**Issue by hhg7** [DrHyde/perl-modules-Statistics-ChiSquare#1]
I might suggest that you change the error "malformed data" from `return "Malformed data!" if(grep { /\D/ } @data);`

I'm not sure if negative values can be put in to a Chi-squared test.  I think that your error is giving the error from the "-" character which is in `\D` character class.  Perhaps the error could be more useful, or negative numbers be allowed?

**Comment by DrHyde** [comment]
Oh gosh, this is oooooold code that I've not used in a looooong time, let me see if I can remember my statistics course from 30 years ago :-)

What this tests isn't the actual values in your data, but the number of times each value occurs. The values can be anything - you could for example have a six sided die labeled [-2, -1, "lemon", 12.4, خ, and "Iä! Iä! Cthulhu fhtagn!"]. But obviously the number of times each value appears when you roll the die a few times will be in ℕ⁰ - no matter how hard you try you can't ever roll "lemon" 6.2 times or -3 times or "squirrel" times. Therefore `\D` isn't allowed.
